MahinaBoutique/ServiceHost/Areas/Administration/Pages/Account/Roles/Create.cshtml.cs
using _0_SelfBuildFramwork.Infrastracture;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Account.Roles
{
    public class CreateModel : PageModel
    {
        public List<SelectListItem> Permission;

        public CreateRole Command { get; set; }
       
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public CreateModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
            Permission = new List<SelectListItem>();
        }

        public void OnGet()
        {
            
            foreach(var expose in _exposers)
            {
                var permissions = expose.Expose();
                foreach(var permission in permissions)
                {
                    var gruop = new SelectListGroup
                    {
                        Name = permission.Key
                    };

                    foreach(var permissiondio in permission.Value)
                    {
                        Permission.Add(new SelectListItem(permissiondio.Name,$"{permissiondio.Name},{permissiondio.Code}")
                        {
                           Group = gruop,
                        });
                    }

                }
            }
        }

        public RedirectToPageResult  OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Account/Roles/Edit.cshtml.cs
using _0_SelfBuildFramwork.Infrastracture;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Account.Roles
{
    public class EditModel : PageModel
    {
        public List<SelectListItem> Permission;

        public EditRole Command{ get; set; }

        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
             Permission = new List<SelectListItem>();
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            foreach(var expose in _exposers)
            {
                var permissions = expose.Expose();
                foreach(var permission in permissions)
                {
                    var gruop = new SelectListGroup
                    {
                        Name = permission.Key
                    };

                    foreach(var permissiondio in permission.Value)
                    {
                        var item = (new SelectListItem(permissiondio.Name,$"{permissiondio.Name},{permissiondio.Code}")
                        {
                           Group = gruop,
                        });
                        Permission.Add(item);
                        
                        foreach(var selectedPermission in Command.PermissionDto)
                        {
                            if(item.Text == selectedPermission.Name)
                            {
                                 item.Selected = true;
                            }
                        }
                    }

                }
            }
        }

        public RedirectToPageResult OnPost(EditRole command)
        {
           _roleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogManagement.Application.Contract.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class CreateModel : PageModel
    {
        public CreateArticle command;
        public SelectList Categories { get; set; }

        private readonly IArticleApplication _articleApplication;

        public CreateModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Categories = new SelectList(_articleApplication.GetArticleCategories(),"Id","Name");
        }

        public RedirectToPageResult OnPost(CreateArticle command)
        {
            var result = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogManagement.Application.Contract.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class EditModel : PageModel
    {
        public EditArticle Command { get; set; }

        public SelectList Categories{get; set; }

        private readonly IArticleApplication _articleApplication;

        public EditModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }


        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            Categories = new SelectList(_articleApplication.GetArticleCategories(),"Id","Name");
        }

        public RedirectToPageResult OnPost(EditArticle command)
        {
            _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Inventory/Index.cshtml.cs
using System.Collections.Generic;
using _0_SelfBuildFramwork.Infrastracture;
using InventoryManagement.Application.Contract.Inventory;
using InventoryManagement.Infrastracture.Config.Permissions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.Product;

namespace ServiceHost.Areas.Administration.Pages.Inventory
{
    [Authorize(Roles = Roles.SystemManager)]
    public class IndexModel : PageModel
    {

        public InventorySearchModel SearchModel { get; set; }

        public SelectList Product;

        public List<InventoryViewModel> Invnetory { get; set; }

        private readonly IProductApplication _products;
        private readonly IInventoryApplication _inventoryApplication;

        public IndexModel(IProductApplication products, IInventoryApplication inventory)
        {
            _products = products;
            _inventoryApplication = inventory;

        }

        [NeedPermission(InventoryPermissions.ListInventory)]
        public void OnGet(InventorySearchModel searchModel)
        {
            Product = new SelectList(_products.GetProducts(), "Id", "Name");
            Invnetory = _inventoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var CreateInventory = new CreateInventory()
            {
                Products = _products.GetProducts()
            };
            return Partial("./Create", CreateInventory);
        }

        [NeedPermission(InventoryPermissions.CreateInventory)]
        public JsonResult OnPostCreate(CreateInventory command)
        {
            var result = _inventoryApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(int id)
        {
            var SelectedItem = _inventoryApplication.GetDetails(id);
            SelectedItem.Products = _products.GetProducts();
            return Partial("./Edit", SelectedItem);
        }
        [NeedPermission(InventoryPermissions.EditInventory)]
        public JsonResult OnPostEdit(EditInventory command)
        {
            var result = _inventoryApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetIncrease(long id)
        {
            var Increase = new IncreaseInventory{
                InventoryId = id
                };
            return Partial("./Increase",Increase);
        }

        [NeedPermission(InventoryPermissions.IncreaseInventory)]
        public JsonResult OnPostIncrease(IncreaseInventory command)
        {
            var result = _inventoryApplication.Increase(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetReduce(long id)
        {
            var reduce = new ReduceInventory
            {
                InventoryId = id
            };
            return Partial("./Reduce",reduce);
        }

        [NeedPermission(InventoryPermissions.ReduceInventory)]
        public JsonResult OnPostReduce(ReduceInventory command)
        {
            var result = _inventoryApplication.Reduce(command);
            return new JsonResult(result);
        }


        [NeedPermission(InventoryPermissions.OperationLogInventory)]
        public IActionResult OnGetOperationLog(long inventoryId)
        {
            var operation = _inventoryApplication.Operations(inventoryId);
            return Partial("./Operation",operation);
        }

    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Inventory/Create.cshtml
@model InventoryManagement.Application.Contract.Inventory.CreateInventory


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد انبار جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
    
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">انتخاب محصول</label>
                    <select asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")' class="form-control">
                        <option value="0">لطفا انتخاب کنید</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UnitPrice" class="control-label">قیمت واحد</label>
                    <input type="number" class="form-control" asp-for="UnitPrice">
                    <span asp-validation-for="UnitPrice" class="error"></span>
                </div>
            </div>
        </div>
        
        
       
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Inventory/Edit.cshtml
@model InventoryManagement.Application.Contract.Inventory.EditInventory


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش انبار</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">انتخاب محصول</label>
                    <select asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")' class="form-control">
                        <option value="0">لطفا انتخاب کنید</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UnitPrice" class="control-label">قیمت واحد</label>
                    <input type="number" class="form-control" asp-for="UnitPrice">
                    <span asp-validation-for="UnitPrice" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Inventory/Increase.cshtml
@model InventoryManagement.Application.Contract.Inventory.IncreaseInventory


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزایش موجودی</h4>
</div>

<form asp-page="./Index" asp-page-handler="Increase"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد محصول</label>
                    <input type="number" class="form-control" asp-for="Count">
                    <span asp-validation-for="Count" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea rows="3" class="form-control autogrow" asp-for="Description"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="InventoryId" value="@Model.InventoryId" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">افزایش</button>
    </div>
</form>

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Inventory/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Inventory.IndexModel
@{
}
@using InventoryManagement.Infrastracture.Config.Permissions
@{
  
    ViewData["title"] = "مدیریت انبار";
}

<div class="row" >
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a Permission = "InventoryPermissions.CreateInventory" class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index","Create")" >ایجاد انبار جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در تخفیفات</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">

                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items="@Model.Product">
                            <option value="0">لطفا محصول را انتخاب کتید....</option>
                        </select>
                    </div>

                    <div class="form-group m-r-10">
                        <div class="checkbox checkbox-primary">
                            <input asp-for="SearchModel.InStock">
                            <label asp-for="SearchModel.InStock">
                                جستجو در ناموجودها
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductsDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست انبارها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>محصول</th>
                                    <th>تاریخ تولید</th>
                                    <th>موجودی</th>
                                    <th>قیمت واحد</th>
                                    <th class="text-center">عملیات</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.Invnetory)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Product</td>
                                        <td>@item.CreaionDate</td>
                                        <td>@item.CurrentCount</td>
                                        <td>@item.UnitPrice</td>
                                        <td class="text-center justify-content-center align-items-center">
                                            <a class="btn btn-warning m-5" Permission="InventoryPermissions.EditInventory" href="#showmodal=@Url.Page("./Index","Edit",new { id = item.Id })">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            <a class="btn btn-success m-5" Permission="InventoryPermissions.IncreaseInventory" href="#showmodal=@Url.Page("./Index","Increase",new { id = item.Id })">
                                                <i class="fa fa-plus"></i> افزایش موجودی
                                            </a>
                                            <a class="btn btn-danger m-5" Permission="InventoryPermissions.ReduceInventory" href="#showmodal=@Url.Page("./Index","Reduce",new { id = item.Id })">
                                                <i class="fa fa-minus"></i> کاهش موجودی
                                            </a>
                                            <a class="btn btn-primary m-5"Permission="InventoryPermissions.OperationLogInventory" onclick="$('.modal-dialog').css('width', '60%')" href="#showmodal=@Url.Page("./Index","OperationLog",new { InventoryId = item.Id })">
                                                <i class="fa fa-recycle"></i> تاریخچه عملیات ها
                                            </a>

                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Inventory/Operation.cshtml
@model List<InventoryManagement.Application.Contract.Inventory.InventoryOperationViewModel>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">گردش محصول</h4>
</div>
<div class="modal-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>تعداد</th>
                    <th>تاریخ</th>
                    <th>عملیات</th>
                    <th>موجودی فعلی</th>
                    <th>عملگر</th>
                    <th>توضیحات</th>
                </tr>
            </thead>
            <tbody>
                
                    @foreach(var item in Model)
                        {
                           <tr class="text-white @(item.Operation ? "bg-success" : "bg-danger")">
                            <td>@item.Id</td>
                            <td>@item.Count</td>
                            <td>@item.OperationTime</td>
                            <td>
                                @if(item.Operation)
                                {
                                <span>ورودی</span>
                                }else
                                {
                                <span>خروجی</span>
                                }
                            </td>
                            <td>@item.CurrentCount</td>
                            <td>@item.Operator</td>
                            <td>@item.Description</td>
                           </tr>
                        }
                
            </tbody>
            </table>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
    </div>

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Inventory/Reduce.cshtml
@model InventoryManagement.Application.Contract.Inventory.ReduceInventory


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">کاهش موجودی</h4>
</div>

<form asp-page="./Index" asp-page-handler="Reduce"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد محصول</label>
                    <input type="number" class="form-control" asp-for="Count">
                    <span asp-validation-for="Count" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <textarea rows="3" class="form-control autogrow" asp-for="Description"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="InventoryId" value="@Model.InventoryId" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">کاهش</button>
    </div>
</form>