MahinaBoutique/ServiceHost/Areas/Administration/Pages/Account/Roles/Create.cshtml.cs
using _0_SelfBuildFramwork.Infrastracture;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Account.Roles
{
    public class CreateModel : PageModel
    {
        public List<SelectListItem> Permission;

        public CreateRole Command { get; set; }
       
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public CreateModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
            Permission = new List<SelectListItem>();
        }

        public void OnGet()
        {
            
            foreach(var expose in _exposers)
            {
                var permissions = expose.Expose();
                foreach(var permission in permissions)
                {
                    var gruop = new SelectListGroup
                    {
                        Name = permission.Key
                    };

                    foreach(var permissiondio in permission.Value)
                    {
                        Permission.Add(new SelectListItem(permissiondio.Name,$"{permissiondio.Name},{permissiondio.Code}")
                        {
                           Group = gruop,
                        });
                    }

                }
            }
        }

        public RedirectToPageResult  OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Account/Roles/Edit.cshtml.cs
using _0_SelfBuildFramwork.Infrastracture;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Account.Roles
{
    public class EditModel : PageModel
    {
        public List<SelectListItem> Permission;

        public EditRole Command{ get; set; }

        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
             Permission = new List<SelectListItem>();
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            foreach(var expose in _exposers)
            {
                var permissions = expose.Expose();
                foreach(var permission in permissions)
                {
                    var gruop = new SelectListGroup
                    {
                        Name = permission.Key
                    };

                    foreach(var permissiondio in permission.Value)
                    {
                        var item = (new SelectListItem(permissiondio.Name,$"{permissiondio.Name},{permissiondio.Code}")
                        {
                           Group = gruop,
                        });
                        Permission.Add(item);
                        
                        foreach(var selectedPermission in Command.PermissionDto)
                        {
                            if(item.Text == selectedPermission.Name)
                            {
                                 item.Selected = true;
                            }
                        }
                    }

                }
            }
        }

        public RedirectToPageResult OnPost(EditRole command)
        {
           _roleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogManagement.Application.Contract.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class CreateModel : PageModel
    {
        public CreateArticle command;
        public SelectList Categories { get; set; }

        private readonly IArticleApplication _articleApplication;

        public CreateModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Categories = new SelectList(_articleApplication.GetArticleCategories(),"Id","Name");
        }

        public RedirectToPageResult OnPost(CreateArticle command)
        {
            var result = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogManagement.Application.Contract.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class EditModel : PageModel
    {
        public EditArticle Command { get; set; }

        public SelectList Categories{get; set; }

        private readonly IArticleApplication _articleApplication;

        public EditModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }


        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            Categories = new SelectList(_articleApplication.GetArticleCategories(),"Id","Name");
        }

        public RedirectToPageResult OnPost(EditArticle command)
        {
            _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/Order/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_SelfBuildFramwork.Infrastracture;
using AccountManagement.Application.Contract.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.Order;
using ShopManagement.Application.Contract.ProductCategory;
using ShopManagment.Infrastracture.Config.Permissions;

namespace ServiceHost.Areas.Administration.Pages.Shop.Order
{
    public class IndexModel : PageModel
    {
       [TempData]
       public string message{get; set;}

        public OrderSearchModel SearchModel { get; set; }

        public List<OrderViewModel> Orders { get; set; }

        public List<OrderItemViewModel> Items { get; set; }

        public SelectList Accounts { get; set; }

        private readonly IOrderApplication _orderApplication;
        private readonly IAccountApplication _accountApplication;

        public IndexModel(IOrderApplication orderApplication, IAccountApplication accountApplication)
        {
            _orderApplication = orderApplication;
            _accountApplication = accountApplication;
            
        }


        public void OnGet(OrderSearchModel searchModel)
        {
            Orders = _orderApplication.Search(searchModel);
            Accounts = new SelectList(_accountApplication.GetAccount(),"Id","FullName");
        }

        public RedirectToPageResult OnGetConfirm(long orderId)
        {
            _orderApplication.CallAdmin();
            var res = _orderApplication.Pay(orderId,0);
           if (res == "")
            {
               message = "موجودی انبار به شما اجازه تایید این سفارش را نمیدهد";
            }
            return RedirectToPage("./Index");
            //need check in inventory
        }

        public RedirectToPageResult OnGetCancel(long orderId)
        {
            _orderApplication.Cancel(orderId);
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetGetItems(long orderId)
        {
            Items = _orderApplication.Getitems(orderId);
            return Partial("./OrderItem",Items);
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/Product/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.Product;
using ShopManagement.Application.Contract.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Shop.Product
{
    public class IndexModel : PageModel
    {
       
        public ProductSearchModel SearchModel { get; set; }

        public SelectList ProductCategories;

        public List<ProductViewModel> Products { get; set; }

        private readonly IProductApplication _products;
        private readonly IProductCategoryApplication _productCategory;

        public IndexModel(IProductApplication products, IProductCategoryApplication productCategory)
        {
            _products = products;
            _productCategory = productCategory;
        }

        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategory.GetList(),"Id","Name");
            Products= _products.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        { 
            var createProduct = new CreateProduct()
            {
                Categories = _productCategory.GetList()
            };
            return Partial("./Create",createProduct);
        }

        public JsonResult OnPostCreate(CreateProduct command)
        {
            var result = _products.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(int id)
        {
            var SelectedItem = _products.GetDetails(id);
            SelectedItem.Categories = _productCategory.GetList();
            return Partial("./Edit",SelectedItem);
        }

        public JsonResult OnPostEdit(EditProduct command)
        {
            var result = _products.Edit(command);
            return new JsonResult(result);
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/ProductCategory/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_SelfBuildFramwork.Infrastracture;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contract.ProductCategory;
using ShopManagment.Infrastracture.Config.Permissions;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategory
{
    public class IndexModel : PageModel
    {
       
        public ProductCategorySearchModel SearchModel { get; set; }

        public List<ProductCategoryViewModel> ProductCategories { get; set; }

        private readonly IProductCategoryApplication _productCategory;

        public IndexModel(IProductCategoryApplication productCategory)
        {
            _productCategory = productCategory;
        }

        [NeedPermission(ShopPermissions.ListProductCategory)]
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategory.Search(searchModel);
        }

        
        public IActionResult OnGetCreate()
        {
            return Partial("./Create",new CreatePoductCategory());
        }

        [NeedPermission(ShopPermissions.CreateProduct)]
        public JsonResult OnPostCreate(CreatePoductCategory command)
        {
            var result = _productCategory.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(int id)
        {
            var SelectedItem = _productCategory.GetDetails(id);
            return Partial("./Edit",SelectedItem);
        }

        [NeedPermission(ShopPermissions.EditProduct)]
        public JsonResult OnPostEdit(EditProductCategory command)
        {
            if (!ModelState.IsValid)
            {

            }
            var result = _productCategory.Edit(command);
            return new JsonResult(result);
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/ProductPicture/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.Product;
using ShopManagement.Application.Contract.ProductCategory;
using ShopManagement.Application.Contract.ProductPicture;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductPicture
{
    public class IndexModel : PageModel
    {
       
        public ProductPictureSearchModel SearchModel { get; set; }

        public SelectList Products;

        public List<ProductPictureViewModel> ProductPictures { get; set; }

        private readonly IProductApplication _products;
        private readonly IProductPictureApplication _productPicture;

        public IndexModel(IProductApplication products, IProductPictureApplication productPicture)
        {
            _products = products;
            _productPicture = productPicture;
        }

        public void OnGet(ProductPictureSearchModel searchModel)
        {
            Products = new SelectList(_products.GetProducts(),"Id","Name");
            ProductPictures =  _productPicture.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        { 
            var createProductPicture = new CreateProductPicture()
            {
                Products = _products.GetProducts()
            };
            return Partial("./Create",createProductPicture);
        }

        public JsonResult OnPostCreate(CreateProductPicture command)
        {
            var result = _productPicture.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(int id)
        {
            var SelectedItem = _productPicture.GetDetails(id);
            SelectedItem.Products = _products.GetProducts();
            return Partial("./Edit",SelectedItem);
        }

        public JsonResult OnPostEdit(EditProductPicture command)
        {
            var result = _productPicture.Edit(command);
            return new JsonResult(result);
        }

        public RedirectToPageResult OnGetRemove(long id)
        {
            var result = _productPicture.Remove(id);
            return RedirectToPage("./Index");
            //we can control server erorr here with result
        }

        public RedirectToPageResult OnGetRestore(long id)
        {
            var result= _productPicture.Restore(id);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/Slide/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.Product;
using ShopManagement.Application.Contract.ProductCategory;
using ShopManagement.Application.Contract.ProductPicture;
using ShopManagement.Application.Contract.Slide;

namespace ServiceHost.Areas.Administration.Pages.Shop.Slide
{
    public class IndexModel : PageModel
    { 
        public List<SlideViewModel> Slides { get; set; }

        private readonly ISlideApplication _slidesApplication;

        public IndexModel(ISlideApplication slides)
        {
            _slidesApplication = slides;
        }

        public void OnGet()
        {
            Slides =  _slidesApplication.GetList();
        }

        public IActionResult OnGetCreate()
        { 
            var createSlides= new CreateSlide();
           
            return Partial("./Create",createSlides);
        }

        public JsonResult OnPostCreate(CreateSlide command)
        {
            var result = _slidesApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(int id)
        {
            var SelectedItem = _slidesApplication.GetDetails(id);
            return Partial("./Edit",SelectedItem);
        }

        public JsonResult OnPostEdit(EditSlide command)
        {
            var result = _slidesApplication.Edit(command);
            return new JsonResult(result);
        }

        public RedirectToPageResult OnGetRemove(long id)
        {
            var result = _slidesApplication.Remove(id);
            return RedirectToPage("./Index");
            //we can control server erorr here with result
        }

        public RedirectToPageResult OnGetRestore(long id)
        {
            var result= _slidesApplication.Restore(id);
            return RedirectToPage("./Index");
        }
    }
}

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/Slide/Create.cshtml
@model ShopManagement.Application.Contract.Slide.CreateSlide


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد اسلاید جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Heading" class="control-label">سرتیتر</label>
                    <input type="text" class="form-control" asp-for="Heading">
                    <span asp-validation-for="Heading" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ButtonText" class="control-label">متن دگمه</label>
                    <input type="text" class="form-control" asp-for="ButtonText">
                    <span asp-validation-for="ButtonText" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Text" class="control-label">متن اسلاید</label>
                    <textarea class="form-control autogrow" asp-for="Text"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Text" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Link" class="control-label">لینک</label>
                    <input type="text" class="form-control" asp-for="Link">
                    <span asp-validation-for="Link" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/Slide/Edit.cshtml
@model ShopManagement.Application.Contract.Slide.EditSlide


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش اسلاید|@Model.Title</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Heading" class="control-label">سرتیتر</label>
                    <input type="text" class="form-control" asp-for="Heading">
                    <span asp-validation-for="Heading" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ButtonText" class="control-label">متن دگمه</label>
                    <input type="text" class="form-control" asp-for="ButtonText">
                    <span asp-validation-for="ButtonText" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="Text" class="control-label">متن اسلاید</label>
                    <textarea class="form-control autogrow" asp-for="Text"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="Text" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Link" class="control-label">لینک</label>
                    <input type="text" class="form-control" asp-for="Link">
                    <span asp-validation-for="Link" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

MahinaBoutique/ServiceHost/Areas/Administration/Pages/Shop/Slide/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Shop.Slide.IndexModel
@{
}

@{
  
    ViewData["title"] = "مدیریت اسلایدر";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index","Create")" >ایجاداسلایدر جدید</a>
        </p>
    </div>
</div>


<div class="row" id="ProductsDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست گروه محصولات</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>تاریخ تولید</th>
                                    <th>وضعیت</th>
                                    <th>عنوان</th>
                                    <th>سرتیتر</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.Slides)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/ProductPictures/@item.Picture" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td class="text-center">
                                            @if(!item.IsRemoved)
                                                {
                                                    <i class="fa fa-2x fa-check text-success"></i>
                                                }else
                                                {
                                                    <i class="fa fa-2x fa-remove text-danger"></i>
                                                }
                                        </td>
                                        <td>@item.Title</td>
                                        <td>@item.Heading</td>
                                        <td class="text-center justify-content-center align-items-center">
                                            <a class="btn btn-warning m-5" href="#showmodal=@Url.Page("./Index","Edit",new { id = item.Id })">
                                                <i class="fa fa-edit">ویرایش</i>
                                            </a>
                                            @if (!item.IsRemoved)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id" class="btn btn-danger btn-custom waves-effect waves-light pt-5 m-5">حذف</a>
                                            }
                                            else
                                            {
                                                <a asp-page="./Index" asp-page-handler="Restore" asp-route-id="@item.Id" class="btn btn-success btn-custom waves-effect waves-light pt-5 m-5">بازگرداندن</a>
                                            }
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}